### ISSUE TITLE
Few things I had to do..

### ISSUE THREAD

**Issue by creationshop** [manoaratefy/ispconfig3-varnish#2]
Hey thanks for the fantastic work you did. I ran in to a few things consistently so wanted to share:

Some issues I ran in to-

1. The symlink isn't being made between the ispconfig plugins available and the enabled folders. If you find that no sites are being made in nginx>sites-enabled then this fixes that-
ln -s /usr/local/ispconfig/server/plugins-available/varnish_plugin.inc.php /usr/local/ispconfig/server/plugins-enabled/varnish_plugin.inc.php

(do this after item 5, below)

2. the sites-enable and sites-available folders aren't being created at installation of nginx -
cd /etc/nginx
mkdir sites-enabled sites-available

3.  delete the default.conf from /etc/nginx/conf.d/

4. edit the ispconfig.conf and change the listening ports.
nano 000-ispconfig.conf
at the bottom you need to change 80 to 6080 and 443 to 6443

5. cp'ing the folder gives an error. cp - R is what worked for me:
cp -r etc/* /etc/

then go to tools > sync and sync the sites as instructed

**Comment by creationshop** [comment]
You could also see this error on restarting nginx;
nginx: [emerg] cannot load certificate "/var/www/clients/client0/web50/ssl/-le.crt":

the solution for me was to go to the sites view in the isp cp, select the domain, and go to the ssl tab and enable spdy. if you dont have a spdy option there, go to server settings and enable it at the ssl area.

**Comment by manoaratefy** [comment]
Hello,

- Symlink has been added to the documentation.
- Folder creation has been added to the documentation.
- Default NGINX configuration file deletion has been added to the documentation.
- No need to edit ISPConfig port (as it doesn't go behind Varnish & NGINX).
- copying command adjusted on the documentation.
- bug about "nginx: [emerg] cannot load certificate" has been fixed (the field "ssl_domain" is empty with ISPConfig when nobodies check the page "SSL". Once someone goes in this page, the field is filled).
